package CalcApp;


/**
* CalcApp/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Monday, 22 April, 2024 6:48:45 PM IST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
